### ISSUE TITLE
Host a Lambda Layer

### ISSUE THREAD

**Issue by vpl-webteam** [Api2Pdf/api2pdf.python#1]
I think it could be helpful to provide a "Layer version ARN" for people that are using lambda.

Makes it easy to attach to a project without having to maintain a lambda layer.

**Comment by apexdodge** [comment]
Thanks for the suggestion. Our API that monitors usage, client balances, billing and top ups, logging, etc is all infrastructure built on Azure, so doing all of this in a lambda layer would not be feasible for us at this time.
