### ISSUE TITLE
Can not import Api2Pdf

### ISSUE THREAD

**Issue by rashad** [Api2Pdf/api2pdf.python#2]
Hello 👋 

I'm trying to run the doc example but I keep getting an import error when I try to run the script `ImportError: cannot import name 'Api2Pdf' from 'api2pdf'`

---
here's the script I'm trying to run
```
from api2pdf import Api2Pdf

a2p_client = Api2Pdf('my_api_key')

api_response = a2p_client.HeadlessChrome.convert_from_html('<p>Hello, World</p>')
print(api_response.result)
```

*version*: `pip freeze` gives me `api2pdf==0.0.11` 

thaaanks a lot for your help 😁

**Comment by apexdodge** [comment]
The script looks correct, but there must be something not setup correctly with your local development environment. Just tested the library right now and works fine: https://s3.amazonaws.com/vo-random/ShareX/2019/10/2019-10-19_08-43-17.gif

Closing issue as not related to the library
