### ISSUE TITLE
Header and footer not displayed in generated pdf

### ISSUE THREAD

**Issue by Smona** [Api2Pdf/api2pdf.python#4]
Hi, I'm currently working on implementing a header and footer in my document, but when calling the HeadlessChrome api with the following code, I get back a PDF with no header or footer.

```py
        margin_x = 0.75
        chrome_options = {
            "marginLeft": margin_x,
            "marginRight": margin_x,
            "marginTop": margin_x,
            "marginBottom": margin_x,
            "displayHeaderFooter": True,
            "headerTemplate": "<span>TestHeader</span>",
            "footerTemplate": "<span>TestFooter</span>",
        }
        response = client.HeadlessChrome.convert_from_html(content, **chrome_options)
```

I've gone over the docs and it looks like everything is correct here. Am I missing something here?

**Comment by apexdodge** [comment]
It's possible that they are actually there, but just too tiny to see with the human eye. That happened to me.

Try the following as header/footer - increases font size.

`"<div class=\"page-footer\" style=\"width:100%; text-align:right; font-size:12px;\">Page <span class=\"pageNumber\"></span> of <span class=\"totalPages\"></span></div>"`

**Comment by Smona** [comment]
Thanks for the advice @apexdodge, unfortunately I came across that in the docs and it didn't help. If I inspect the PDF DOM using that string as the footerTemplate, i find no reference to `page-footer`.

**Comment by apexdodge** [comment]
Can you test out the payload and verify the payload itself works first by following this article: https://www.api2pdf.com/how-to-use-api2pdfs-swaggerhub-to-get-the-most-out-of-our-support-team/

If it works there, it'll be isolated to the python library

**Comment by Smona** [comment]
Aha, looks like you were actually correct! I *ass*umed that the header and footer html would appear in the inspector but they don't. And when I tested your previous template, I didn't have `"displayHeaderFooter"` set (removed it out of desperation while debugging :man_facepalming:). Thanks for the support!
