### ISSUE TITLE
Spaces in a2p_client.HeadlessChrome.convert_from_html breaks filename

### ISSUE THREAD

**Issue by Overdrivr** [Api2Pdf/api2pdf.python#5]
When calling:
```
from api2pdf import Api2Pdf
a2p_client = Api2Pdf('token')
html = "<html code>"
res = a2p_client.HeadlessChrome.convert_from_html(html, file_name='Devis FOO.pdf')
```

The returned PDF carries as name all characters prior to the first space in file_name. Here, it is:

```
Devis
```
without the end of the `file_name` nor the PDF file extension. 

Is this a known bug ?

**Comment by apexdodge** [comment]
Unknown, but I think this goes beyond the scope of what the library and service should handle. File names are part of the content-disposition header and should be encoded correctly. See discussion here: https://stackoverflow.com/questions/93551/how-to-encode-the-filename-parameter-of-content-disposition-header-in-http

In your case, you should replace spaces with %20 so it would be 'Devis%20FOO.pdf'
