### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by ope-john** [Api2Pdf/api2pdf.python#7]
On the heroku log it shows TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a Api2PdfResponse.

**Comment by apexdodge** [comment]
This is not an issue with the python client library, but an issue with your code.

You are probably returning the api2pdf response object by itself. But you should call the result property like so:

![image](https://user-images.githubusercontent.com/777005/84580034-4b20c480-ada1-11ea-90f2-b389582af473.png)

This is just a guess based on your error message as we don't have any other information available to us. Closing as non-issue.
