### ISSUE TITLE
Issue when trying to download a file (typo)

### ISSUE THREAD

**Issue by CamLamb** [Api2Pdf/api2pdf.python#9]
When I generate a PDF or image using:

```python
image_api_response = a2p_client.Chrome.html_to_image(html, file_name=image_filename)
pdf_api_response = a2p_client.Chrome.html_to_pdf(html,file_name=pdf_filename,)
```

To download the file I try to use `image_api_response.download_pdf()` or `pdf_api_response.download_pdf()` I get the following error:

```
File "/usr/local/lib/python3.8/site-packages/api2pdf/api2pdf.py", line 158, in download_pdf
    if self.result['success']:
```

The immediate fix:
https://github.com/Api2Pdf/api2pdf.python/blob/05ea971abda8aa57974db62d58e6678fe2dfb6ad/api2pdf/api2pdf.py#L158
should reference `Success` not `success`

I also recommend a change in this method's name since it isn't only used to download images. Perhaps `download_file`.

**Comment by CamLamb** [comment]
PR for typo fix: https://github.com/Api2Pdf/api2pdf.python/pull/10
PR for rename(optional/probably needs furhter thought) : https://github.com/Api2Pdf/api2pdf.python/pull/11

**Comment by apexdodge** [comment]
Nice job, reviewed them, and merged.

I'll deploy to the package manager as well.
